// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Gleam contributors

// Zig target code generation.
//
// This is an early slice of the backend: it supports module functions over
// ints, floats, bools, strings and Nil, with let bindings, blocks, pipes,
// echo, panic and todo. Everything else panics with "zig codegen" in the
// message. All values use the uniform `Value` union defined in
// templates/prelude.zig, and all memory is leaked (Perceus RC comes later).

use std::collections::HashSet;

use ecow::EcoString;
use src_span::{LineNumbers, SrcSpan};

use crate::ast::{
    ArgNames, AssignmentKind, BinOp, Pattern, Statement, TypedAssignment, TypedExpr,
    TypedFunction, TypedModule, TypedStatement,
};
use crate::type_::{PRELUDE_MODULE_NAME, ValueConstructorVariant};

pub const PRELUDE: &str = include_str!("../templates/prelude.zig");

const INDENT: &str = "    ";

pub fn module(
    module: &TypedModule,
    line_numbers: &LineNumbers,
    src_path: &str,
    prelude_import_path: &str,
) -> String {
    let mut out = String::new();
    out.push_str("// Generated by the Gleam compiler. Do not edit.\n");
    out.push_str(&format!(
        "const P = @import(\"{prelude_import_path}\");\nconst Value = P.Value;\n\n"
    ));

    // Imports, type definitions and constants are not part of this slice of
    // the backend. Uses of them fail in expression codegen, so skipping their
    // declarations here cannot mis-compile.
    for function in &module.definitions.functions {
        let mut generator = FunctionGenerator::new(line_numbers, src_path);
        out.push_str(&generator.function(function));
        out.push('\n');
    }
    out
}

struct FunctionGenerator<'a> {
    line_numbers: &'a LineNumbers,
    src_path: &'a str,
    /// Source name -> rendered name currently in scope.
    scope: im::HashMap<EcoString, EcoString>,
    /// All rendered names used in this function, for unique renaming of
    /// shadowed bindings.
    used_names: HashSet<EcoString>,
    block_counter: usize,
}

impl<'a> FunctionGenerator<'a> {
    fn new(line_numbers: &'a LineNumbers, src_path: &'a str) -> Self {
        Self {
            line_numbers,
            src_path,
            scope: im::HashMap::new(),
            used_names: HashSet::new(),
            block_counter: 0,
        }
    }

    fn function(&mut self, function: &TypedFunction) -> String {
        let name = function
            .name
            .as_ref()
            .map(|(_, name)| name.clone())
            .expect("zig codegen: anonymous top level function");

        let mut parameters = Vec::new();
        for argument in &function.arguments {
            let rendered = match &argument.names {
                ArgNames::Named { name, .. } | ArgNames::NamedLabelled { name, .. } => {
                    self.bind(name)
                }
                ArgNames::Discard { name, .. } | ArgNames::LabelledDiscard { name, .. } => {
                    // Zig has no discard parameters; bind under the `_name`
                    // and discard in the body below.
                    self.bind(name)
                }
            };
            parameters.push(rendered);
        }

        let visibility = if function.publicity.is_private() {
            ""
        } else {
            "pub "
        };
        let parameter_list = parameters
            .iter()
            .map(|p| format!("{}: Value", zig_identifier(p)))
            .collect::<Vec<_>>()
            .join(", ");

        let body = self.statements(&function.body, true, INDENT);

        // Discard parameters the body never references: zig errors on unused
        // parameters, and also on pointless discards, so check usage.
        let mut discards = String::new();
        for parameter in &parameters {
            if !text_uses_name(&body, parameter) {
                discards.push_str(&format!("{INDENT}_ = {};\n", zig_identifier(parameter)));
            }
        }

        format!("{visibility}fn {}({parameter_list}) Value {{\n{discards}{body}}}\n", zig_identifier(&name))
    }

    /// Render a statement sequence. When `is_return_position` the value of
    /// the final statement is returned (function body) otherwise it is broken
    /// out of the enclosing labelled block, which `block` sets up.
    fn statements(
        &mut self,
        statements: &[TypedStatement],
        is_return_position: bool,
        indent: &str,
    ) -> String {
        let saved_scope = self.scope.clone();
        let mut rendered_statements: Vec<String> = Vec::new();

        let last_index = statements.len() - 1;
        for (index, statement) in statements.iter().enumerate() {
            let is_last = index == last_index;
            let rendered = match statement {
                Statement::Expression(expression) => {
                    let value = self.expression(expression, indent);
                    if is_last {
                        format!("{indent}{} {value};\n", exit_keyword(is_return_position))
                    } else {
                        format!("{indent}_ = {value};\n")
                    }
                }
                Statement::Assignment(assignment) => {
                    self.assignment(assignment, is_last, is_return_position, indent)
                }
                Statement::Use(use_) => {
                    let value = self.expression(&use_.call, indent);
                    if is_last {
                        format!("{indent}{} {value};\n", exit_keyword(is_return_position))
                    } else {
                        format!("{indent}_ = {value};\n")
                    }
                }
                Statement::Assert(_) => panic!("zig codegen: assert is not supported yet"),
            };
            rendered_statements.push(rendered);
        }

        // Zig errors on unused local constants, so bindings that are never
        // referenced afterwards get an explicit discard. Rendered names are
        // unique within a function, making the textual scan sound.
        let mut out = String::new();
        for (index, rendered) in rendered_statements.iter().enumerate() {
            out.push_str(rendered);
            if let Statement::Assignment(assignment) = &statements[index] {
                if let Pattern::Variable { name, .. } = &assignment.pattern {
                    let rendered_name = self
                        .scope
                        .get(name)
                        .expect("zig codegen: binding disappeared from scope")
                        .clone();
                    let rest = &rendered_statements[index + 1..];
                    let used_later = rest.iter().any(|text| text_uses_name(text, &rendered_name));
                    if !used_later && !(index == last_index) {
                        out.push_str(&format!(
                            "{indent}_ = {};\n",
                            zig_identifier(&rendered_name)
                        ));
                    }
                }
            }
        }

        self.scope = saved_scope;
        out
    }

    fn assignment(
        &mut self,
        assignment: &TypedAssignment,
        is_last: bool,
        is_return_position: bool,
        indent: &str,
    ) -> String {
        if !matches!(assignment.kind, AssignmentKind::Let | AssignmentKind::Generated) {
            panic!("zig codegen: let assert is not supported yet");
        }
        let value = self.expression(&assignment.value, indent);
        match &assignment.pattern {
            Pattern::Variable { name, .. } => {
                let rendered = self.bind(name);
                let mut out = format!(
                    "{indent}const {} = {value};\n",
                    zig_identifier(&rendered)
                );
                if is_last {
                    out.push_str(&format!(
                        "{indent}{} {};\n",
                        exit_keyword(is_return_position),
                        zig_identifier(&rendered)
                    ));
                }
                out
            }
            Pattern::Discard { .. } => {
                if is_last {
                    format!(
                        "{indent}{} {value};\n",
                        exit_keyword(is_return_position)
                    )
                } else {
                    format!("{indent}_ = {value};\n")
                }
            }
            _ => panic!("zig codegen: pattern destructuring is not supported yet"),
        }
    }

    fn expression(&mut self, expression: &TypedExpr, indent: &str) -> String {
        match expression {
            TypedExpr::Int { int_value, .. } => format!("P.intValue({int_value})"),

            TypedExpr::Float { value, .. } => format!("P.floatValue({value})"),

            TypedExpr::String { value, .. } => {
                format!("P.stringValue(\"{}\")", zig_string_contents(value))
            }

            TypedExpr::Block { statements, .. } => {
                self.labelled_block(statements.as_slice(), indent)
            }

            TypedExpr::Pipeline {
                first_value,
                assignments,
                finally,
                ..
            } => {
                let label = self.next_block_label();
                let inner_indent = format!("{indent}{INDENT}");
                let mut out = format!("{label}: {{\n");
                let saved_scope = self.scope.clone();

                let first = self.expression(&first_value.value, &inner_indent);
                let first_name = self.bind(&first_value.name);
                out.push_str(&format!(
                    "{inner_indent}const {} = {first};\n",
                    zig_identifier(&first_name)
                ));
                for (assignment, _kind) in assignments {
                    let value = self.expression(&assignment.value, &inner_indent);
                    let name = self.bind(&assignment.name);
                    out.push_str(&format!(
                        "{inner_indent}const {} = {value};\n",
                        zig_identifier(&name)
                    ));
                }
                let finally = self.expression(finally, &inner_indent);
                out.push_str(&format!("{inner_indent}break :{label} {finally};\n"));
                out.push_str(&format!("{indent}}}"));
                self.scope = saved_scope;
                out
            }

            TypedExpr::Var {
                constructor, name, ..
            } => self.variable(name, &constructor.variant),

            TypedExpr::Call { fun, arguments, .. } => {
                let rendered_arguments = arguments
                    .iter()
                    .map(|argument| self.expression(&argument.value, indent))
                    .collect::<Vec<_>>()
                    .join(", ");
                let target = self.call_target(fun);
                format!("{target}({rendered_arguments})")
            }

            TypedExpr::BinOp {
                operator,
                left,
                right,
                ..
            } => {
                let left = self.expression(left, indent);
                let right = self.expression(right, indent);
                self.binary_operator(*operator, &left, &right)
            }

            TypedExpr::Echo {
                expression,
                location,
                ..
            } => {
                let inner = expression
                    .as_ref()
                    .expect("zig codegen: echo with no expression");
                let value = self.expression(inner, indent);
                let line = self.line_number(location);
                format!("P.echo({value}, \"{}\", {line})", self.src_path)
            }

            TypedExpr::Panic {
                message, location, ..
            } => {
                let message = self.panic_message(message.as_deref(), "panic expression evaluated", indent);
                let line = self.line_number(location);
                format!("P.gleamPanic({message}, \"{}\", {line})", self.src_path)
            }

            TypedExpr::Todo {
                message, location, ..
            } => {
                let message =
                    self.panic_message(message.as_deref(), "todo expression evaluated", indent);
                let line = self.line_number(location);
                format!("P.gleamPanic({message}, \"{}\", {line})", self.src_path)
            }

            TypedExpr::NegateInt { value, .. } => {
                format!("P.negateInt({})", self.expression(value, indent))
            }

            TypedExpr::NegateBool { value, .. } => {
                format!("P.negateBool({})", self.expression(value, indent))
            }

            _ => panic!(
                "zig codegen: expression is not supported yet: {expression:?}"
            ),
        }
    }

    fn panic_message(
        &mut self,
        message: Option<&TypedExpr>,
        default: &str,
        indent: &str,
    ) -> String {
        match message {
            Some(message) => format!("({}).string", self.expression(message, indent)),
            None => format!("\"{default}\""),
        }
    }

    fn variable(&mut self, name: &EcoString, variant: &ValueConstructorVariant) -> String {
        match variant {
            ValueConstructorVariant::LocalVariable { .. } => {
                let rendered = self
                    .scope
                    .get(name)
                    .unwrap_or_else(|| panic!("zig codegen: variable {name} not in scope"))
                    .clone();
                zig_identifier(&rendered)
            }
            ValueConstructorVariant::Record { name, module, .. }
                if module == PRELUDE_MODULE_NAME =>
            {
                match name.as_str() {
                    "True" => "P.TRUE".to_string(),
                    "False" => "P.FALSE".to_string(),
                    "Nil" => "P.NIL".to_string(),
                    _ => panic!("zig codegen: prelude constructor {name} is not supported yet"),
                }
            }
            ValueConstructorVariant::ModuleFn { .. } => {
                panic!("zig codegen: functions as values are not supported yet")
            }
            _ => panic!("zig codegen: variable {name} ({variant:?}) is not supported yet"),
        }
    }

    fn call_target(&mut self, fun: &TypedExpr) -> String {
        match fun {
            TypedExpr::Var { constructor, .. } => match &constructor.variant {
                ValueConstructorVariant::ModuleFn { name, module, .. } => {
                    // Calls stay within the current module in this slice;
                    // the type checker guarantees the function exists.
                    let _ = module;
                    zig_identifier(name)
                }
                _ => panic!("zig codegen: only module function calls are supported yet"),
            },
            _ => panic!("zig codegen: only direct function calls are supported yet"),
        }
    }

    fn binary_operator(&self, operator: BinOp, left: &str, right: &str) -> String {
        let helper = match operator {
            BinOp::And => {
                return format!("P.boolValue(if (({left}).bool) ({right}).bool else false)");
            }
            BinOp::Or => {
                return format!("P.boolValue(if (({left}).bool) true else ({right}).bool)");
            }
            BinOp::Eq => "eq",
            BinOp::NotEq => "notEq",
            BinOp::LtInt => "ltInt",
            BinOp::LtEqInt => "ltEqInt",
            BinOp::GtInt => "gtInt",
            BinOp::GtEqInt => "gtEqInt",
            BinOp::LtFloat => "ltFloat",
            BinOp::LtEqFloat => "ltEqFloat",
            BinOp::GtFloat => "gtFloat",
            BinOp::GtEqFloat => "gtEqFloat",
            BinOp::AddInt => "addInt",
            BinOp::SubInt => "subInt",
            BinOp::MultInt => "multInt",
            BinOp::DivInt => "divInt",
            BinOp::RemainderInt => "remainderInt",
            BinOp::AddFloat => "addFloat",
            BinOp::SubFloat => "subFloat",
            BinOp::MultFloat => "multFloat",
            BinOp::DivFloat => "divFloat",
            BinOp::Concatenate => "concatenate",
        };
        format!("P.{helper}({left}, {right})")
    }

    fn labelled_block(&mut self, statements: &[TypedStatement], indent: &str) -> String {
        let label = self.next_block_label();
        let inner_indent = format!("{indent}{INDENT}");
        let body = self.statements_with_break(statements, &label, &inner_indent);
        format!("{label}: {{\n{body}{indent}}}")
    }

    fn statements_with_break(
        &mut self,
        statements: &[TypedStatement],
        label: &str,
        indent: &str,
    ) -> String {
        // `statements` renders `return`/`break` from a placeholder keyword;
        // patch the break label in afterwards.
        let rendered = self.statements(statements, false, indent);
        rendered.replace(BREAK_PLACEHOLDER, &format!("break :{label}"))
    }

    fn next_block_label(&mut self) -> String {
        let label = format!("blk{}", self.block_counter);
        self.block_counter += 1;
        label
    }

    fn line_number(&self, location: &SrcSpan) -> u32 {
        self.line_numbers.line_number(location.start)
    }

    /// Bind a source-level name, renaming to keep rendered names unique
    /// within the function so shadowing works and usage scans are exact.
    fn bind(&mut self, name: &EcoString) -> EcoString {
        let mut rendered: EcoString = name.clone();
        let mut counter = 0;
        while self.used_names.contains(&rendered) {
            counter += 1;
            rendered = EcoString::from(format!("{name}${counter}"));
        }
        let _ = self.used_names.insert(rendered.clone());
        let _ = self.scope.insert(name.clone(), rendered.clone());
        rendered
    }
}

const BREAK_PLACEHOLDER: &str = "\u{1}break\u{1}";

fn exit_keyword(is_return_position: bool) -> &'static str {
    if is_return_position {
        "return"
    } else {
        BREAK_PLACEHOLDER
    }
}

/// Quote an identifier with zig's raw identifier syntax. This side-steps
/// zig keyword collisions and allows `$` in generated names.
fn zig_identifier(name: &str) -> String {
    format!("@\"{name}\"")
}

/// True if the rendered zig text references the rendered variable `name`.
fn text_uses_name(text: &str, name: &str) -> bool {
    text.contains(&zig_identifier(name))
}

/// Gleam string literal contents are close enough to zig's escape syntax to
/// pass through, except form feed which zig does not support.
fn zig_string_contents(value: &str) -> String {
    value.replace("\\f", "\\x0C")
}
