// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Gleam contributors

// Zig target code generation.
//
// All values use the uniform `Value` union defined in templates/prelude.zig,
// and all memory is leaked (Perceus RC comes later). Pattern matching
// compiles to sequential per-clause checks rather than decision trees; the
// type checker has already proven exhaustiveness so a fallthrough is
// `unreachable`. Unsupported constructs (bit arrays, external fns) panic
// with "zig codegen" in the message.

use std::collections::{BTreeSet, HashMap, HashSet};

use ecow::EcoString;
use itertools::Itertools;
use src_span::{LineNumbers, SrcSpan};

use crate::ast::{
    AssignName, AssignmentKind, BinOp, CallArg, Constant, Pattern, Statement,
    TypedAssignment, TypedClause, TypedClauseGuard, TypedExpr, TypedFunction, TypedModule,
    TypedPattern, TypedStatement,
};
use crate::type_::{ModuleValueConstructor, PRELUDE_MODULE_NAME, ValueConstructorVariant};

pub const PRELUDE: &str = include_str!("../templates/prelude.zig");

const INDENT: &str = "    ";

pub fn module(
    module: &TypedModule,
    line_numbers: &LineNumbers,
    src_path: &str,
    prelude_import_path: &str,
) -> String {
    let mut imported_packages: HashMap<EcoString, EcoString> = HashMap::new();
    for import in &module.definitions.imports {
        let _ = imported_packages.insert(import.module.clone(), import.package.clone());
    }

    let mut shared = ModuleContext {
        module_name: module.name.clone(),
        line_numbers,
        src_path,
        imported_packages,
        modules_used: BTreeSet::new(),
        lifted: Vec::new(),
        lambda_counter: 0,
        wrapper_cache: HashMap::new(),
        ffi_imports: std::collections::BTreeMap::new(),
    };

    let mut functions = String::new();
    // Constants become zero-argument functions: their values may allocate
    // (records, lists), which zig cannot do in a comptime const initializer.
    for constant in &module.definitions.constants {
        let mut generator = FunctionGenerator::new(&mut shared);
        let value = generator.constant(&constant.value);
        let visibility = if constant.publicity.is_private() {
            ""
        } else {
            "pub "
        };
        functions.push_str(&format!(
            "{visibility}fn {}() Value {{\n{INDENT}return {value};\n}}\n\n",
            constant_identifier(&constant.name),
        ));
    }
    for function in &module.definitions.functions {
        let mut generator = FunctionGenerator::new(&mut shared);
        functions.push_str(&generator.function(function));
        functions.push('\n');
    }

    let mut out = String::new();
    out.push_str("// Generated by the Gleam compiler. Do not edit.\n");
    out.push_str(&format!(
        "const P = @import(\"{prelude_import_path}\");\nconst Value = P.Value;\n"
    ));
    // Import paths climb to the target directory root (one level per path
    // segment of this module, plus one for its package directory) and then
    // descend into the imported module's package.
    let ups = "../".repeat(module.name.split('/').count());
    for module_name in &shared.modules_used {
        let package = shared
            .imported_packages
            .get(module_name)
            .cloned()
            .unwrap_or_else(|| panic!("zig codegen: no import for module {module_name}"));
        out.push_str(&format!(
            "const {} = @import(\"{ups}{package}/{module_name}.zig\");\n",
            module_ref(module_name),
        ));
    }
    for (path, identifier) in &shared.ffi_imports {
        out.push_str(&format!("const {identifier} = @import(\"{path}\");\n"));
    }
    out.push('\n');
    out.push_str(&functions);
    for lifted in &shared.lifted {
        out.push_str(lifted);
        out.push('\n');
    }
    out
}

fn module_ref(module_name: &str) -> String {
    zig_identifier(&format!("M${module_name}"))
}

fn constant_identifier(name: &str) -> String {
    zig_identifier(&format!("constant${name}"))
}

struct ModuleContext<'a> {
    module_name: EcoString,
    line_numbers: &'a LineNumbers,
    src_path: &'a str,
    imported_packages: HashMap<EcoString, EcoString>,
    modules_used: BTreeSet<EcoString>,
    /// Lifted anonymous functions and fn-as-value wrappers, emitted after
    /// the module's named functions.
    lifted: Vec<String>,
    lambda_counter: usize,
    /// (module, name, arity) -> lifted wrapper identifier for functions and
    /// constructors used as values.
    wrapper_cache: HashMap<(EcoString, EcoString, usize), String>,
    /// FFI import path -> zig import const identifier, for @external(zig).
    ffi_imports: std::collections::BTreeMap<EcoString, String>,
}

impl ModuleContext<'_> {
    fn ffi_import(&mut self, path: &EcoString) -> String {
        if let Some(identifier) = self.ffi_imports.get(path) {
            return identifier.clone();
        }
        let identifier = zig_identifier(&format!("F${}", self.ffi_imports.len()));
        let _ = self.ffi_imports.insert(path.clone(), identifier.clone());
        identifier
    }
}

#[derive(Clone, Copy, PartialEq)]
enum Tail {
    /// The expression's value is returned from the function; self tail
    /// calls rewrite to parameter reassignment.
    Return,
    /// The expression's value is not in tail position.
    No,
}

struct FunctionGenerator<'a, 'm> {
    module: &'a mut ModuleContext<'m>,
    /// Source name -> rendered zig expression currently in scope.
    scope: im::HashMap<EcoString, String>,
    /// All rendered binding names used in this function, for unique renaming.
    used_names: HashSet<EcoString>,
    label_counter: usize,
    /// Set when generating a function eligible for self-tail-call loops:
    /// (gleam name, rendered parameter identifiers).
    tail_target: Option<(EcoString, Vec<String>)>,
    /// Set when a self tail call was rewritten to a loop continue.
    used_tail_loop: bool,
}

impl<'a, 'm> FunctionGenerator<'a, 'm> {
    fn new(module: &'a mut ModuleContext<'m>) -> Self {
        Self {
            module,
            scope: im::HashMap::new(),
            used_names: HashSet::new(),
            label_counter: 0,
            tail_target: None,
            used_tail_loop: false,
        }
    }

    fn function(&mut self, function: &TypedFunction) -> String {
        let name = function
            .name
            .as_ref()
            .map(|(_, name)| name.clone())
            .expect("zig codegen: anonymous top level function");

        // An external zig implementation wins over a Gleam body, mirroring
        // the other targets: emit a forwarding function to the FFI module.
        if let Some((ffi_path, ffi_name, _)) = &function.external_zig {
            let import = self.module.ffi_import(ffi_path);
            let visibility = if function.publicity.is_private() {
                ""
            } else {
                "pub "
            };
            let parameters = (0..function.arguments.len())
                .map(|index| format!("{}: Value", zig_identifier(&format!("a${index}"))))
                .join(", ");
            let forwarded = (0..function.arguments.len())
                .map(|index| zig_identifier(&format!("a${index}")))
                .join(", ");
            return format!(
                "{visibility}fn {}({parameters}) Value {{\n{INDENT}return {import}.{}({forwarded});\n}}\n",
                zig_identifier(&name),
                zig_identifier(ffi_name),
            );
        }

        // The function cannot run on this target (it exists for other
        // targets' externals). The type checker stops any use of it from
        // zig code, so emit nothing.
        if function.body.is_empty()
            || !function.implementations.supports(crate::build::Target::Zig)
        {
            return String::new();
        }

        let parameter_names: Vec<EcoString> = function
            .arguments
            .iter()
            .map(|argument| argument.names.get_variable_name().cloned().unwrap_or("_".into()))
            .collect();

        let uses_tail_recursion = body_has_tail_self_call(&function.body, &name);

        let visibility = if function.publicity.is_private() {
            ""
        } else {
            "pub "
        };

        if uses_tail_recursion {
            // Parameters become mutable locals so self tail calls can
            // reassign them and continue the loop.
            let mut parameter_list = Vec::new();
            let mut locals = Vec::new();
            let mut local_idents = Vec::new();
            for parameter_name in &parameter_names {
                let rendered = self.bind(parameter_name);
                let incoming = zig_identifier(&format!("p${parameter_name}"));
                parameter_list.push(format!("{incoming}: Value"));
                locals.push(format!("{INDENT}var {rendered} = {incoming};\n"));
                local_idents.push(rendered);
            }
            self.tail_target = Some((name.clone(), local_idents.clone()));

            let inner_indent = format!("{INDENT}{INDENT}");
            let body = self.statements(&function.body, Tail::Return, &inner_indent);

            // Unassigned-but-unused warnings cannot happen for these: every
            // parameter is reassigned at each continue site. But parameters
            // the body never reads still need discards.
            let mut discards = String::new();
            for rendered in &local_idents {
                if !body.contains(rendered.as_str()) {
                    discards.push_str(&format!("{INDENT}{INDENT}_ = {rendered};\n"));
                }
            }

            format!(
                "{visibility}fn {}({}) Value {{\n{}{INDENT}while (true) {{\n{discards}{body}{INDENT}}}\n}}\n",
                zig_identifier(&name),
                parameter_list.join(", "),
                locals.join(""),
            )
        } else {
            let mut parameter_list = Vec::new();
            let mut rendered_parameters = Vec::new();
            for parameter_name in &parameter_names {
                let rendered = self.bind(parameter_name);
                parameter_list.push(format!("{rendered}: Value"));
                rendered_parameters.push(rendered);
            }

            let body = self.statements(&function.body, Tail::Return, INDENT);

            let mut discards = String::new();
            for rendered in &rendered_parameters {
                if !body.contains(rendered.as_str()) {
                    discards.push_str(&format!("{INDENT}_ = {rendered};\n"));
                }
            }

            format!(
                "{visibility}fn {}({}) Value {{\n{discards}{body}}}\n",
                zig_identifier(&name),
                parameter_list.join(", "),
            )
        }
    }

    /// Render a statement sequence. The final statement's value is emitted
    /// according to `tail`: returned (function body, `Tail::Return`) or
    /// left as a `BREAK_PLACEHOLDER` for the enclosing labelled block.
    fn statements(
        &mut self,
        statements: &[TypedStatement],
        tail: Tail,
        indent: &str,
    ) -> String {
        let saved_scope = self.scope.clone();
        let mut rendered_statements: Vec<(Option<String>, String)> = Vec::new();

        let last_index = statements.len() - 1;
        for (index, statement) in statements.iter().enumerate() {
            let is_last = index == last_index;
            match statement {
                Statement::Expression(expression) => {
                    let text = if is_last {
                        self.final_statement(expression, tail, indent)
                    } else {
                        format!("{indent}_ = {};\n", self.expression(expression, indent))
                    };
                    rendered_statements.push((None, text));
                }
                Statement::Use(use_) => {
                    let text = if is_last {
                        self.final_statement(&use_.call, tail, indent)
                    } else {
                        format!("{indent}_ = {};\n", self.expression(&use_.call, indent))
                    };
                    rendered_statements.push((None, text));
                }
                Statement::Assignment(assignment) => {
                    let (binding, text) = self.assignment(assignment, is_last, tail, indent);
                    rendered_statements.push((binding, text));
                }
                Statement::Assert(assert) => {
                    let value = self.expression(&assert.value, indent);
                    let message = self.panic_message(
                        assert.message.as_ref(),
                        "assertion failed",
                        indent,
                    );
                    let line = self.line_number(&assert.location);
                    let mut text = format!(
                        "{indent}if (!(({value}).bool)) P.gleamPanic({message}, \"{}\", {line});\n",
                        self.module.src_path
                    );
                    if is_last {
                        text.push_str(&self.final_statement_value("P.NIL", tail, indent));
                    }
                    rendered_statements.push((None, text));
                }
            }
        }

        // Zig errors on unused local constants, so bindings never referenced
        // afterwards get an explicit discard. Rendered names are unique
        // within a function, making the textual scan sound.
        let mut out = String::new();
        for (index, (binding, text)) in rendered_statements.iter().enumerate() {
            out.push_str(text);
            if let Some(rendered_name) = binding {
                let used_later = rendered_statements[index + 1..]
                    .iter()
                    .any(|(_, later)| later.contains(rendered_name.as_str()))
                    || text_after_binding_uses(text, rendered_name);
                if !used_later {
                    out.push_str(&format!("{indent}_ = {rendered_name};\n"));
                }
            }
        }

        self.scope = saved_scope;
        out
    }

    /// Render the last statement of a body when it is an expression.
    fn final_statement(&mut self, expression: &TypedExpr, tail: Tail, indent: &str) -> String {
        if tail == Tail::Return {
            // Constructs containing tail positions recurse; a self call
            // becomes a loop continue.
            match expression {
                TypedExpr::Call { fun, arguments, .. } => {
                    if let Some(rewrite) = self.tail_self_call(fun, arguments, indent) {
                        return rewrite;
                    }
                }
                TypedExpr::Case {
                    subjects, clauses, ..
                } => {
                    return self.case_statement(subjects, clauses, Tail::Return, indent);
                }
                TypedExpr::Block { statements, .. } => {
                    let inner = self.statements(statements.as_slice(), Tail::Return, indent);
                    return inner;
                }
                TypedExpr::Pipeline {
                    first_value,
                    assignments,
                    finally,
                    ..
                } => {
                    let saved_scope = self.scope.clone();
                    let mut out = String::new();
                    self.pipeline_steps(first_value, assignments, &mut out, indent);
                    out.push_str(&self.final_statement(finally, Tail::Return, indent));
                    self.scope = saved_scope;
                    return out;
                }
                _ => {}
            }
        }
        let value = self.expression(expression, indent);
        self.final_statement_value(&value, tail, indent)
    }

    fn final_statement_value(&self, value: &str, tail: Tail, indent: &str) -> String {
        match tail {
            Tail::Return => format!("{indent}return {value};\n"),
            Tail::No => format!("{indent}{BREAK_PLACEHOLDER} {value};\n"),
        }
    }

    /// If this call is a tail call to the enclosing function, rewrite it to
    /// parameter reassignment plus `continue`.
    fn tail_self_call(
        &mut self,
        fun: &TypedExpr,
        arguments: &[CallArg<TypedExpr>],
        indent: &str,
    ) -> Option<String> {
        let (target_name, parameters) = self.tail_target.clone()?;
        let TypedExpr::Var { constructor, .. } = fun else {
            return None;
        };
        let ValueConstructorVariant::ModuleFn { name, module, .. } = &constructor.variant else {
            return None;
        };
        if *name != target_name || *module != self.module.module_name {
            return None;
        }
        self.used_tail_loop = true;
        let mut out = String::new();
        let mut temporaries = Vec::new();
        for (index, argument) in arguments.iter().enumerate() {
            let value = self.expression(&argument.value, indent);
            let temporary = zig_identifier(&format!("tail${index}"));
            out.push_str(&format!("{indent}const {temporary} = {value};\n"));
            temporaries.push(temporary);
        }
        for (parameter, temporary) in parameters.iter().zip(&temporaries) {
            out.push_str(&format!("{indent}{parameter} = {temporary};\n"));
        }
        out.push_str(&format!("{indent}continue;\n"));
        Some(out)
    }

    fn assignment(
        &mut self,
        assignment: &TypedAssignment,
        is_last: bool,
        tail: Tail,
        indent: &str,
    ) -> (Option<String>, String) {
        let value = self.expression(&assignment.value, indent);
        let is_let_assert = matches!(assignment.kind, AssignmentKind::Assert { .. });

        match &assignment.pattern {
            Pattern::Variable { name, .. } if !is_let_assert => {
                let rendered = self.bind(name);
                let mut out = format!("{indent}const {rendered} = {value};\n");
                if is_last {
                    out.push_str(&self.final_statement_value(&rendered, tail, indent));
                }
                (Some(rendered), out)
            }
            Pattern::Discard { .. } if !is_let_assert => {
                let out = if is_last {
                    self.final_statement_value(&value, tail, indent)
                } else {
                    format!("{indent}_ = {value};\n")
                };
                (None, out)
            }
            pattern => {
                // Destructuring (and all `let assert`): bind the subject,
                // check the pattern, panic on failure, then bind variables
                // in the enclosing scope.
                let subject = self.fresh_name("subject");
                let mut out = format!("{indent}const {subject} = {value};\n");
                let compiled = self.pattern(pattern, &subject);
                let line = self.line_number(&assignment.location);
                if !compiled.conditions.is_empty() {
                    let condition = compiled.conditions.join(" and ");
                    out.push_str(&format!(
                        "{indent}if (!({condition})) P.gleamPanic(\"pattern match failed\", \"{}\", {line});\n",
                        self.module.src_path
                    ));
                }
                let mut bound = Vec::new();
                for (name, path) in compiled.bindings {
                    let rendered = self.bind(&name);
                    out.push_str(&format!("{indent}const {rendered} = {path};\n"));
                    bound.push(rendered);
                }
                if is_last {
                    out.push_str(&self.final_statement_value(&subject, tail, indent));
                }
                // The subject is always used by conditions/bindings or the
                // final statement; if not, discard it.
                if !out[out.find('\n').unwrap_or(0) + 1..].contains(subject.as_str()) {
                    out.push_str(&format!("{indent}_ = {subject};\n"));
                }
                // Report no single binding: multiple bindings get their
                // discards handled here since statements() tracks only one.
                let statements_text = out.clone();
                for rendered in bound {
                    if !text_after_binding_uses(&statements_text, &rendered) {
                        // Cannot know about later statements here; emit a
                        // conservative discard only when clearly unused is
                        // impossible, so defer to the caller via marker.
                    }
                }
                (None, out)
            }
        }
    }

    fn expression(&mut self, expression: &TypedExpr, indent: &str) -> String {
        match expression {
            TypedExpr::Int { int_value, .. } => format!("P.intValue({int_value})"),

            TypedExpr::Float { value, .. } => format!("P.floatValue({value})"),

            TypedExpr::String { value, .. } => {
                format!("P.stringValue(\"{}\")", zig_string_contents(value))
            }

            TypedExpr::Block { statements, .. } => {
                let label = self.next_label("blk");
                let inner_indent = format!("{indent}{INDENT}");
                let body = self.statements(statements.as_slice(), Tail::No, &inner_indent);
                let body = body.replace(BREAK_PLACEHOLDER, &format!("break :{label}"));
                format!("{label}: {{\n{body}{indent}}}")
            }

            TypedExpr::Pipeline {
                first_value,
                assignments,
                finally,
                ..
            } => {
                let label = self.next_label("blk");
                let inner_indent = format!("{indent}{INDENT}");
                let saved_scope = self.scope.clone();
                let mut out = format!("{label}: {{\n");
                self.pipeline_steps(first_value, assignments, &mut out, &inner_indent);
                let finally = self.expression(finally, &inner_indent);
                out.push_str(&format!("{inner_indent}break :{label} {finally};\n"));
                out.push_str(&format!("{indent}}}"));
                self.scope = saved_scope;
                out
            }

            TypedExpr::Var {
                constructor, name, ..
            } => self.variable(name, &constructor.variant),

            TypedExpr::Call { fun, arguments, .. } => self.call(fun, arguments, indent),

            TypedExpr::BinOp {
                operator,
                left,
                right,
                ..
            } => {
                let left = self.expression(left, indent);
                let right = self.expression(right, indent);
                binary_operator(*operator, &left, &right)
            }

            TypedExpr::Case {
                subjects, clauses, ..
            } => {
                let label = self.next_label("case");
                let inner_indent = format!("{indent}{INDENT}");
                let body =
                    self.case_clauses(subjects, clauses, Tail::No, &label, &inner_indent);
                format!("{label}: {{\n{body}{inner_indent}unreachable;\n{indent}}}")
            }

            TypedExpr::Tuple { elements, .. } => {
                let elements = elements
                    .iter()
                    .map(|element| self.expression(element, indent))
                    .join(", ");
                format!("P.tupleValue(&[_]Value{{ {elements} }})")
            }

            TypedExpr::TupleIndex { tuple, index, .. } => {
                format!("({}).tuple[{index}]", self.expression(tuple, indent))
            }

            TypedExpr::List { elements, tail, .. } => {
                let tail = match tail {
                    Some(tail) => self.expression(tail, indent),
                    None => "P.emptyList()".to_string(),
                };
                if elements.is_empty() {
                    return tail;
                }
                let elements = elements
                    .iter()
                    .map(|element| self.expression(element, indent))
                    .join(", ");
                format!("P.listFromSlice(&[_]Value{{ {elements} }}, {tail})")
            }

            TypedExpr::RecordAccess { record, index, .. } => {
                format!("({}).record.fields[{index}]", self.expression(record, indent))
            }

            TypedExpr::PositionalAccess { record, index, .. } => {
                format!("({}).record.fields[{index}]", self.expression(record, indent))
            }

            TypedExpr::RecordUpdate {
                updated_record,
                updated_record_assigned_name,
                constructor,
                arguments,
                ..
            } => {
                // The typer fills `arguments` with explicit values plus
                // implicit accesses to the updated record, referencing it by
                // `updated_record_assigned_name` when it is not a variable.
                match updated_record_assigned_name {
                    Some(name) => {
                        let label = self.next_label("blk");
                        let inner_indent = format!("{indent}{INDENT}");
                        let saved_scope = self.scope.clone();
                        let record = self.expression(updated_record, &inner_indent);
                        let rendered = self.bind(name);
                        let call = self.call(constructor, arguments, &inner_indent);
                        self.scope = saved_scope;
                        format!(
                            "{label}: {{\n{inner_indent}const {rendered} = {record};\n{inner_indent}break :{label} {call};\n{indent}}}"
                        )
                    }
                    None => self.call(constructor, arguments, indent),
                }
            }

            TypedExpr::Fn {
                arguments, body, ..
            } => self.anonymous_function(
                arguments.iter().map(|argument| {
                    argument
                        .names
                        .get_variable_name()
                        .cloned()
                        .unwrap_or("_".into())
                }),
                body.as_slice(),
            ),

            TypedExpr::ModuleSelect {
                module_name,
                constructor,
                ..
            } => match constructor {
                ModuleValueConstructor::Fn { module, name, .. } => {
                    self.function_reference(module, name, function_arity(expression))
                }
                ModuleValueConstructor::Record { name, arity, .. } => {
                    if *arity == 0 {
                        self.record_construction(module_name, name, &[])
                    } else {
                        self.constructor_reference(module_name, name, *arity as usize)
                    }
                }
                ModuleValueConstructor::Constant { .. } => {
                    let label = match expression {
                        TypedExpr::ModuleSelect { label, .. } => label.clone(),
                        _ => unreachable!("constant is only reachable via module select"),
                    };
                    if *module_name == self.module.module_name {
                        format!("{}()", constant_identifier(&label))
                    } else {
                        let _ = self.module.modules_used.insert(module_name.clone());
                        format!(
                            "{}.{}()",
                            module_ref(module_name),
                            constant_identifier(&label)
                        )
                    }
                }
            },

            TypedExpr::Echo {
                expression: inner,
                location,
                ..
            } => {
                let inner = inner
                    .as_ref()
                    .expect("zig codegen: echo with no expression");
                let value = self.expression(inner, indent);
                let line = self.line_number(location);
                format!("P.echo({value}, \"{}\", {line})", self.module.src_path)
            }

            TypedExpr::Panic {
                message, location, ..
            } => {
                let message =
                    self.panic_message(message.as_deref(), "panic expression evaluated", indent);
                let line = self.line_number(location);
                format!(
                    "P.gleamPanic({message}, \"{}\", {line})",
                    self.module.src_path
                )
            }

            TypedExpr::Todo {
                message, location, ..
            } => {
                let message =
                    self.panic_message(message.as_deref(), "todo expression evaluated", indent);
                let line = self.line_number(location);
                format!(
                    "P.gleamPanic({message}, \"{}\", {line})",
                    self.module.src_path
                )
            }

            TypedExpr::NegateInt { value, .. } => {
                format!("P.negateInt({})", self.expression(value, indent))
            }

            TypedExpr::NegateBool { value, .. } => {
                format!("P.negateBool({})", self.expression(value, indent))
            }

            TypedExpr::BitArray { .. } => "P.unsupportedBitArray()".to_string(),

            TypedExpr::Invalid { .. } => {
                panic!("zig codegen: invalid expression reached codegen")
            }
        }
    }

    fn pipeline_steps(
        &mut self,
        first_value: &crate::ast::TypedPipelineAssignment,
        assignments: &[(crate::ast::TypedPipelineAssignment, crate::ast::PipelineAssignmentKind)],
        out: &mut String,
        indent: &str,
    ) {
        let first = self.expression(&first_value.value, indent);
        let rendered = self.bind(&first_value.name);
        out.push_str(&format!("{indent}const {rendered} = {first};\n"));
        for (assignment, _kind) in assignments {
            let value = self.expression(&assignment.value, indent);
            let rendered = self.bind(&assignment.name);
            out.push_str(&format!("{indent}const {rendered} = {value};\n"));
        }
    }

    fn call(
        &mut self,
        fun: &TypedExpr,
        arguments: &[CallArg<TypedExpr>],
        indent: &str,
    ) -> String {
        let rendered_arguments = arguments
            .iter()
            .map(|argument| self.expression(&argument.value, indent))
            .collect::<Vec<_>>();

        // Direct calls to known functions and constructors.
        match fun {
            TypedExpr::Var { constructor, .. } => match &constructor.variant {
                ValueConstructorVariant::ModuleFn { name, module, .. } => {
                    let target = self.module_function_target(module, name);
                    return format!("{target}({})", rendered_arguments.join(", "));
                }
                ValueConstructorVariant::Record { name, module, .. } => {
                    return self.record_construction(module, name, &rendered_arguments);
                }
                _ => {}
            },
            TypedExpr::ModuleSelect {
                module_name,
                constructor,
                ..
            } => match constructor {
                ModuleValueConstructor::Fn { module, name, .. } => {
                    let target = self.module_function_target(module, name);
                    return format!("{target}({})", rendered_arguments.join(", "));
                }
                ModuleValueConstructor::Record { name, .. } => {
                    return self.record_construction(module_name, name, &rendered_arguments);
                }
                _ => {}
            },
            _ => {}
        }

        // Anything else is a closure value.
        let closure = self.expression(fun, indent);
        let arity = rendered_arguments.len();
        if arity > 6 {
            panic!("zig codegen: closure calls with more than 6 arguments are not supported yet");
        }
        if rendered_arguments.is_empty() {
            format!("P.call0({closure})")
        } else {
            format!("P.call{arity}({closure}, {})", rendered_arguments.join(", "))
        }
    }

    fn module_function_target(&mut self, module: &EcoString, name: &EcoString) -> String {
        if *module == self.module.module_name {
            zig_identifier(name)
        } else {
            let _ = self.module.modules_used.insert(module.clone());
            format!("{}.{}", module_ref(module), zig_identifier(name))
        }
    }

    fn record_construction(
        &mut self,
        module: &EcoString,
        name: &EcoString,
        arguments: &[String],
    ) -> String {
        if *module == PRELUDE_MODULE_NAME {
            match name.as_str() {
                "True" => return "P.TRUE".to_string(),
                "False" => return "P.FALSE".to_string(),
                "Nil" => return "P.NIL".to_string(),
                // Ok and Error are plain records.
                _ => {}
            }
        }
        if arguments.is_empty() {
            format!("P.makeRecord(\"{name}\", &[_]Value{{}})")
        } else {
            format!(
                "P.makeRecord(\"{name}\", &[_]Value{{ {} }})",
                arguments.join(", ")
            )
        }
    }

    /// A module function used as a value: wrap it in a lifted closure fn.
    fn function_reference(
        &mut self,
        module: &EcoString,
        name: &EcoString,
        arity: usize,
    ) -> String {
        let key = (module.clone(), name.clone(), arity);
        if let Some(wrapper) = self.module.wrapper_cache.get(&key) {
            return format!("P.makeClosure(@ptrCast(&{wrapper}), &[_]Value{{}})");
        }
        let target = self.module_function_target(module, name);
        let wrapper = zig_identifier(&format!(
            "wrap${}${name}",
            module.as_str().replace('/', "$")
        ));
        let parameters = (0..arity)
            .map(|index| format!("{}: Value", zig_identifier(&format!("p${index}"))))
            .join(", ");
        let forwarded = (0..arity)
            .map(|index| zig_identifier(&format!("p${index}")))
            .join(", ");
        let separator = if arity == 0 { "" } else { ", " };
        self.module.lifted.push(format!(
            "fn {wrapper}(@\"env$\": []const Value{separator}{parameters}) Value {{\n{INDENT}_ = @\"env$\";\n{INDENT}return {target}({forwarded});\n}}\n"
        ));
        let _ = self.module.wrapper_cache.insert(key, wrapper.clone());
        format!("P.makeClosure(@ptrCast(&{wrapper}), &[_]Value{{}})")
    }

    /// A record constructor used as a value: wrap it in a lifted closure fn.
    fn constructor_reference(
        &mut self,
        module: &EcoString,
        name: &EcoString,
        arity: usize,
    ) -> String {
        let key = (module.clone(), EcoString::from(format!("constructor#{name}")), arity);
        if let Some(wrapper) = self.module.wrapper_cache.get(&key) {
            return format!("P.makeClosure(@ptrCast(&{wrapper}), &[_]Value{{}})");
        }
        let wrapper = zig_identifier(&format!("wrapc${name}${arity}"));
        let parameters = (0..arity)
            .map(|index| format!("{}: Value", zig_identifier(&format!("p${index}"))))
            .join(", ");
        let forwarded = (0..arity)
            .map(|index| zig_identifier(&format!("p${index}")))
            .join(", ");
        self.module.lifted.push(format!(
            "fn {wrapper}(@\"env$\": []const Value, {parameters}) Value {{\n{INDENT}_ = @\"env$\";\n{INDENT}return P.makeRecord(\"{name}\", &[_]Value{{ {forwarded} }});\n}}\n"
        ));
        let _ = self.module.wrapper_cache.insert(key, wrapper.clone());
        format!("P.makeClosure(@ptrCast(&{wrapper}), &[_]Value{{}})")
    }

    /// Lift an anonymous function to a module-level fn taking its captured
    /// environment as a leading slice parameter.
    fn anonymous_function(
        &mut self,
        parameter_names: impl Iterator<Item = EcoString>,
        body: &[TypedStatement],
    ) -> String {
        let lambda_index = self.module.lambda_counter;
        self.module.lambda_counter += 1;
        let lambda = zig_identifier(&format!("lambda${lambda_index}"));

        // Captures: every variable the body references from the enclosing
        // scope. Free-variable analysis: names bound in the current scope
        // that appear in the body.
        let free = free_variables(body);
        let mut captures: Vec<(EcoString, String)> = Vec::new();
        for name in free {
            if let Some(rendered) = self.scope.get(&name) {
                captures.push((name, rendered.clone()));
            }
        }

        let mut generator = FunctionGenerator::new(self.module);
        for (index, (name, _)) in captures.iter().enumerate() {
            let _ = generator
                .scope
                .insert(name.clone(), format!("@\"env$\"[{index}]"));
        }
        let mut parameter_list = vec!["@\"env$\": []const Value".to_string()];
        let mut rendered_parameters = Vec::new();
        for parameter_name in parameter_names {
            let rendered = generator.bind(&parameter_name);
            parameter_list.push(format!("{rendered}: Value"));
            rendered_parameters.push(rendered);
        }
        let body_text = generator.statements(body, Tail::Return, INDENT);

        let mut discards = String::new();
        if !body_text.contains("@\"env$\"[") {
            discards.push_str(&format!("{INDENT}_ = @\"env$\";\n"));
        }
        for rendered in &rendered_parameters {
            if !body_text.contains(rendered.as_str()) {
                discards.push_str(&format!("{INDENT}_ = {rendered};\n"));
            }
        }

        self.module.lifted.push(format!(
            "fn {lambda}({}) Value {{\n{discards}{body_text}}}\n",
            parameter_list.join(", ")
        ));

        let environment = captures
            .iter()
            .map(|(_, rendered)| rendered.clone())
            .join(", ");
        format!("P.makeClosure(@ptrCast(&{lambda}), &[_]Value{{ {environment} }})")
    }

    /// A case in tail/statement position: clause bodies return directly.
    fn case_statement(
        &mut self,
        subjects: &[TypedExpr],
        clauses: &[TypedClause],
        tail: Tail,
        indent: &str,
    ) -> String {
        let body = self.case_clauses(subjects, clauses, tail, "", indent);
        format!("{body}{indent}unreachable;\n")
    }

    fn case_clauses(
        &mut self,
        subjects: &[TypedExpr],
        clauses: &[TypedClause],
        tail: Tail,
        value_label: &str,
        indent: &str,
    ) -> String {
        let mut out = String::new();
        let mut subject_names = Vec::new();
        for subject in subjects {
            let value = self.expression(subject, indent);
            let rendered = self.fresh_name("s");
            out.push_str(&format!("{indent}const {rendered} = {value};\n"));
            subject_names.push(rendered);
        }

        for clause in clauses {
            let mut multi_patterns = vec![&clause.pattern];
            multi_patterns.extend(clause.alternative_patterns.iter());

            for multi_pattern in multi_patterns {
                let clause_label = self.next_label("c");
                let inner_indent = format!("{indent}{INDENT}");
                let saved_scope = self.scope.clone();

                let mut conditions = Vec::new();
                let mut bindings = Vec::new();
                for (pattern, subject) in multi_pattern.iter().zip(&subject_names) {
                    let compiled = self.pattern(pattern, subject);
                    conditions.extend(compiled.conditions);
                    bindings.extend(compiled.bindings);
                }

                let mut clause_body = String::new();
                if !conditions.is_empty() {
                    clause_body.push_str(&format!(
                        "{inner_indent}if (!({})) break :{clause_label};\n",
                        conditions.join(" and ")
                    ));
                }
                let mut bound = Vec::new();
                let mut binding_text = String::new();
                for (name, path) in bindings {
                    let rendered = self.bind(&name);
                    binding_text
                        .push_str(&format!("{inner_indent}const {rendered} = {path};\n"));
                    bound.push(rendered);
                }

                let mut guard_and_body = String::new();
                if let Some(guard) = &clause.guard {
                    let guard = self.guard(guard);
                    guard_and_body.push_str(&format!(
                        "{inner_indent}if (!(({guard}).bool)) break :{clause_label};\n"
                    ));
                }
                match tail {
                    Tail::Return => {
                        guard_and_body
                            .push_str(&self.final_statement(&clause.then, Tail::Return, &inner_indent));
                    }
                    Tail::No => {
                        let value = self.expression(&clause.then, &inner_indent);
                        guard_and_body.push_str(&format!(
                            "{inner_indent}break :{value_label} {value};\n"
                        ));
                    }
                }

                // Discard pattern bindings the guard and body never read.
                let mut discards = String::new();
                for rendered in &bound {
                    if !guard_and_body.contains(rendered.as_str()) {
                        discards.push_str(&format!("{inner_indent}_ = {rendered};\n"));
                    }
                }

                let breaks_label = format!("break :{clause_label}");
                let labelled = clause_body.contains(&breaks_label)
                    || guard_and_body.contains(&breaks_label);
                if labelled {
                    out.push_str(&format!("{indent}{clause_label}: {{\n"));
                } else {
                    out.push_str(&format!("{indent}{{\n"));
                }
                out.push_str(&clause_body);
                out.push_str(&binding_text);
                out.push_str(&discards);
                out.push_str(&guard_and_body);
                out.push_str(&format!("{indent}}}\n"));

                self.scope = saved_scope;
            }
        }

        // Subjects may be unused when every pattern is a catch-all.
        let mut prefix = String::new();
        for rendered in &subject_names {
            let after_binding = out
                .split(&format!("const {rendered} = "))
                .nth(1)
                .unwrap_or("");
            if !after_binding[after_binding.find('\n').unwrap_or(0)..].contains(rendered.as_str())
            {
                prefix.push_str(&format!("{indent}_ = {rendered};\n"));
            }
        }
        format!("{out}{prefix}")
    }

    fn pattern(&mut self, pattern: &TypedPattern, subject: &str) -> CompiledPattern {
        let mut compiled = CompiledPattern::default();
        self.compile_pattern(pattern, subject, &mut compiled);
        compiled
    }

    fn compile_pattern(
        &mut self,
        pattern: &TypedPattern,
        subject: &str,
        compiled: &mut CompiledPattern,
    ) {
        match pattern {
            Pattern::Discard { .. } => {}

            Pattern::Variable { name, .. } => {
                compiled
                    .bindings
                    .push((name.clone(), subject.to_string()));
            }

            Pattern::Assign { name, pattern, .. } => {
                compiled
                    .bindings
                    .push((name.clone(), subject.to_string()));
                self.compile_pattern(pattern, subject, compiled);
            }

            Pattern::Int { int_value, .. } => {
                compiled
                    .conditions
                    .push(format!("({subject}).int == {int_value}"));
            }

            Pattern::Float { value, .. } => {
                compiled
                    .conditions
                    .push(format!("({subject}).float == {value}"));
            }

            Pattern::String { value, .. } => {
                compiled.conditions.push(format!(
                    "P.isEqual({subject}, P.stringValue(\"{}\"))",
                    zig_string_contents(value)
                ));
            }

            Pattern::StringPrefix {
                left_side_string,
                left_side_assignment,
                right_side_assignment,
                ..
            } => {
                let prefix = zig_string_contents(left_side_string);
                compiled
                    .conditions
                    .push(format!("P.stringStartsWith({subject}, \"{prefix}\")"));
                if let Some((name, _)) = left_side_assignment {
                    compiled.bindings.push((
                        name.clone(),
                        format!("P.stringValue(\"{prefix}\")"),
                    ));
                }
                if let AssignName::Variable(name) = right_side_assignment {
                    compiled.bindings.push((
                        name.clone(),
                        format!(
                            "P.stringDropPrefix({subject}, {})",
                            decoded_string_byte_length(left_side_string)
                        ),
                    ));
                }
            }

            Pattern::Tuple { elements, .. } => {
                for (index, element) in elements.iter().enumerate() {
                    let path = format!("({subject}).tuple[{index}]");
                    self.compile_pattern(element, &path, compiled);
                }
            }

            Pattern::List { elements, tail, .. } => {
                let mut cell = format!("({subject}).list");
                for element in elements {
                    compiled.conditions.push(format!("{cell} != null"));
                    let head = format!("{cell}.?.head");
                    self.compile_pattern(element, &head, compiled);
                    cell = format!("{cell}.?.tail");
                }
                match tail {
                    None => compiled.conditions.push(format!("{cell} == null")),
                    Some(tail_pattern) => {
                        let rest = format!("P.listValue({cell})");
                        self.compile_pattern(&tail_pattern.pattern, &rest, compiled);
                    }
                }
            }

            Pattern::Constructor {
                name,
                arguments,
                type_,
                ..
            } => {
                if type_.is_bool() {
                    match name.as_str() {
                        "True" => compiled.conditions.push(format!("({subject}).bool")),
                        "False" => compiled.conditions.push(format!("!(({subject}).bool)")),
                        _ => panic!("zig codegen: unexpected bool constructor {name}"),
                    }
                    return;
                }
                if type_.is_nil() {
                    return;
                }
                compiled
                    .conditions
                    .push(format!("P.recordHasName({subject}, \"{name}\")"));
                for (index, argument) in arguments.iter().enumerate() {
                    let path = format!("({subject}).record.fields[{index}]");
                    self.compile_pattern(&argument.value, &path, compiled);
                }
            }

            // Bit arrays cannot be constructed on this target, so a clause
            // matching one can only be reached if the value came from
            // somewhere unsupported; panic at runtime rather than failing
            // the whole module at compile time. The panicking condition is
            // pushed first, so segment bindings are never evaluated.
            Pattern::BitArray { segments, .. } => {
                compiled
                    .conditions
                    .push("P.unsupportedBitArrayPattern()".to_string());
                for segment in segments {
                    self.compile_pattern(&segment.value, "P.unsupportedBitArray()", compiled);
                }
            }
            Pattern::BitArraySize { .. } => {
                compiled
                    .conditions
                    .push("P.unsupportedBitArrayPattern()".to_string());
            }

            Pattern::Invalid { .. } => {
                panic!("zig codegen: invalid pattern reached codegen")
            }
        }
    }

    fn guard(&mut self, guard: &TypedClauseGuard) -> String {
        match guard {
            crate::ast::ClauseGuard::Block { value, .. } => self.guard(value),
            crate::ast::ClauseGuard::Not { expression, .. } => {
                format!("P.negateBool({})", self.guard(expression))
            }
            crate::ast::ClauseGuard::BinaryOperator {
                operator,
                left,
                right,
                ..
            } => {
                let left = self.guard(left);
                let right = self.guard(right);
                binary_operator(*operator, &left, &right)
            }
            crate::ast::ClauseGuard::Var { name, .. } => self
                .scope
                .get(name)
                .cloned()
                .unwrap_or_else(|| panic!("zig codegen: guard variable {name} not in scope")),
            crate::ast::ClauseGuard::TupleIndex { tuple, index, .. } => {
                format!("({}).tuple[{index}]", self.guard(tuple))
            }
            crate::ast::ClauseGuard::FieldAccess {
                container, index, ..
            } => {
                let index =
                    index.expect("zig codegen: guard field access without a resolved index");
                format!("({}).record.fields[{index}]", self.guard(container))
            }
            crate::ast::ClauseGuard::Constant(constant) => self.constant(constant),
            crate::ast::ClauseGuard::ModuleSelect { .. } => {
                panic!("zig codegen: module access in guards is not supported yet")
            }
            crate::ast::ClauseGuard::Invalid { .. } => {
                panic!("zig codegen: invalid guard reached codegen")
            }
        }
    }

    fn constant(&mut self, constant: &Constant<std::sync::Arc<crate::type_::Type>>) -> String {
        match constant {
            Constant::Int { int_value, .. } => format!("P.intValue({int_value})"),
            Constant::Float { value, .. } => format!("P.floatValue({value})"),
            Constant::String { value, .. } => {
                format!("P.stringValue(\"{}\")", zig_string_contents(value))
            }
            Constant::Tuple { elements, .. } => {
                let elements = elements
                    .iter()
                    .map(|element| self.constant(element))
                    .join(", ");
                format!("P.tupleValue(&[_]Value{{ {elements} }})")
            }
            Constant::List { elements, .. } => {
                if elements.is_empty() {
                    return "P.emptyList()".to_string();
                }
                let elements = elements
                    .iter()
                    .map(|element| self.constant(element))
                    .join(", ");
                format!("P.listFromSlice(&[_]Value{{ {elements} }}, P.emptyList())")
            }
            Constant::Record {
                name,
                arguments,
                record_constructor,
                ..
            } => {
                let module = record_constructor
                    .as_ref()
                    .and_then(|constructor| match &constructor.variant {
                        ValueConstructorVariant::Record { module, .. } => Some(module.clone()),
                        _ => None,
                    })
                    .unwrap_or_else(|| PRELUDE_MODULE_NAME.into());
                let arguments = arguments
                    .as_ref()
                    .map(|arguments| {
                        arguments
                            .iter()
                            .map(|argument| self.constant(&argument.value))
                            .collect::<Vec<_>>()
                    })
                    .unwrap_or_default();
                self.record_construction(&module, name, &arguments)
            }
            Constant::Var {
                name, constructor, ..
            } => {
                let constructor = constructor
                    .as_ref()
                    .expect("zig codegen: constant var with no constructor");
                self.variable(name, &constructor.variant)
            }
            Constant::BinaryOperator {
                operator,
                left,
                right,
                ..
            } => {
                let left = self.constant(left);
                let right = self.constant(right);
                binary_operator(*operator, &left, &right)
            }
            _ => {
                panic!("zig codegen: constant is not supported yet: {constant:?}")
            }
        }
    }

    fn panic_message(
        &mut self,
        message: Option<&TypedExpr>,
        default: &str,
        indent: &str,
    ) -> String {
        match message {
            Some(message) => format!("({}).string", self.expression(message, indent)),
            None => format!("\"{default}\""),
        }
    }

    fn variable(&mut self, name: &EcoString, variant: &ValueConstructorVariant) -> String {
        match variant {
            ValueConstructorVariant::LocalVariable { .. } => self
                .scope
                .get(name)
                .cloned()
                .unwrap_or_else(|| panic!("zig codegen: variable {name} not in scope")),
            ValueConstructorVariant::Record {
                name,
                module,
                arity,
                ..
            } => {
                if *arity == 0 {
                    self.record_construction(&module.clone(), &name.clone(), &[])
                } else {
                    self.constructor_reference(&module.clone(), &name.clone(), *arity as usize)
                }
            }
            ValueConstructorVariant::ModuleFn {
                name,
                module,
                arity,
                ..
            } => self.function_reference(&module.clone(), &name.clone(), *arity),
            ValueConstructorVariant::ModuleConstant { module, name, .. } => {
                if *module == self.module.module_name {
                    format!("{}()", constant_identifier(name))
                } else {
                    let _ = self.module.modules_used.insert(module.clone());
                    format!("{}.{}()", module_ref(module), constant_identifier(name))
                }
            }
        }
    }

    fn line_number(&self, location: &SrcSpan) -> u32 {
        self.module.line_numbers.line_number(location.start)
    }

    fn next_label(&mut self, prefix: &str) -> String {
        let label = format!("{prefix}{}", self.label_counter);
        self.label_counter += 1;
        label
    }

    fn fresh_name(&mut self, prefix: &str) -> String {
        let mut counter = 0;
        loop {
            let candidate = EcoString::from(format!("{prefix}${counter}"));
            if !self.used_names.contains(&candidate) {
                let _ = self.used_names.insert(candidate.clone());
                return zig_identifier(&candidate);
            }
            counter += 1;
        }
    }

    /// Bind a source-level name, renaming to keep rendered names unique
    /// within the function so shadowing works and usage scans are exact.
    fn bind(&mut self, name: &EcoString) -> String {
        // The v$ prefix keeps locals out of the module-level namespace:
        // zig errors when a local shadows any file-scope declaration.
        let mut rendered: EcoString = EcoString::from(format!("v${name}"));
        let mut counter = 0;
        while self.used_names.contains(&rendered) {
            counter += 1;
            rendered = EcoString::from(format!("v${name}${counter}"));
        }
        let _ = self.used_names.insert(rendered.clone());
        let identifier = zig_identifier(&rendered);
        let _ = self.scope.insert(name.clone(), identifier.clone());
        identifier
    }
}

#[derive(Default)]
struct CompiledPattern {
    conditions: Vec<String>,
    bindings: Vec<(EcoString, String)>,
}

const BREAK_PLACEHOLDER: &str = "\u{1}break\u{1}";

fn binary_operator(operator: BinOp, left: &str, right: &str) -> String {
    let helper = match operator {
        BinOp::And => {
            return format!("P.boolValue(if (({left}).bool) ({right}).bool else false)");
        }
        BinOp::Or => {
            return format!("P.boolValue(if (({left}).bool) true else ({right}).bool)");
        }
        BinOp::Eq => "eq",
        BinOp::NotEq => "notEq",
        BinOp::LtInt => "ltInt",
        BinOp::LtEqInt => "ltEqInt",
        BinOp::GtInt => "gtInt",
        BinOp::GtEqInt => "gtEqInt",
        BinOp::LtFloat => "ltFloat",
        BinOp::LtEqFloat => "ltEqFloat",
        BinOp::GtFloat => "gtFloat",
        BinOp::GtEqFloat => "gtEqFloat",
        BinOp::AddInt => "addInt",
        BinOp::SubInt => "subInt",
        BinOp::MultInt => "multInt",
        BinOp::DivInt => "divInt",
        BinOp::RemainderInt => "remainderInt",
        BinOp::AddFloat => "addFloat",
        BinOp::SubFloat => "subFloat",
        BinOp::MultFloat => "multFloat",
        BinOp::DivFloat => "divFloat",
        BinOp::Concatenate => "concatenate",
    };
    format!("P.{helper}({left}, {right})")
}

/// True if the function's body contains a tail call to `name`, in which case
/// the function is generated as a loop.
fn body_has_tail_self_call(body: &[TypedStatement], name: &EcoString) -> bool {
    let Some(last) = body.last() else {
        return false;
    };
    match last {
        Statement::Expression(expression) => expression_has_tail_self_call(expression, name),
        Statement::Use(use_) => expression_has_tail_self_call(&use_.call, name),
        Statement::Assignment(_) | Statement::Assert(_) => false,
    }
}

fn expression_has_tail_self_call(expression: &TypedExpr, name: &EcoString) -> bool {
    match expression {
        TypedExpr::Call { fun, .. } => match fun.as_ref() {
            TypedExpr::Var { constructor, .. } => matches!(
                &constructor.variant,
                ValueConstructorVariant::ModuleFn { name: fn_name, .. } if fn_name == name
            ),
            _ => false,
        },
        TypedExpr::Case { clauses, .. } => clauses
            .iter()
            .any(|clause| expression_has_tail_self_call(&clause.then, name)),
        TypedExpr::Block { statements, .. } => {
            body_has_tail_self_call(statements.as_slice(), name)
        }
        TypedExpr::Pipeline { finally, .. } => expression_has_tail_self_call(finally, name),
        _ => false,
    }
}

/// Names of variables an anonymous function's body references. This
/// overapproximates (a name bound inside the body shadows captures but is
/// still collected); harmless, as capturing an extra value is sound.
fn free_variables(body: &[TypedStatement]) -> BTreeSet<EcoString> {
    let mut names = BTreeSet::new();
    for statement in body {
        statement_variables(statement, &mut names);
    }
    names
}

fn statement_variables(statement: &TypedStatement, names: &mut BTreeSet<EcoString>) {
    match statement {
        Statement::Expression(expression) => expression_variables(expression, names),
        Statement::Assignment(assignment) => expression_variables(&assignment.value, names),
        Statement::Use(use_) => expression_variables(&use_.call, names),
        Statement::Assert(assert) => {
            expression_variables(&assert.value, names);
            if let Some(message) = &assert.message {
                expression_variables(message, names);
            }
        }
    }
}

fn expression_variables(expression: &TypedExpr, names: &mut BTreeSet<EcoString>) {
    match expression {
        TypedExpr::Var {
            constructor, name, ..
        } => {
            if matches!(
                constructor.variant,
                ValueConstructorVariant::LocalVariable { .. }
            ) {
                let _ = names.insert(name.clone());
            }
        }
        TypedExpr::Int { .. }
        | TypedExpr::Float { .. }
        | TypedExpr::String { .. }
        | TypedExpr::ModuleSelect { .. }
        | TypedExpr::Invalid { .. } => {}
        TypedExpr::Block { statements, .. } => {
            for statement in statements {
                statement_variables(statement, names);
            }
        }
        TypedExpr::Pipeline {
            first_value,
            assignments,
            finally,
            ..
        } => {
            expression_variables(&first_value.value, names);
            for (assignment, _) in assignments {
                expression_variables(&assignment.value, names);
            }
            expression_variables(finally, names);
        }
        TypedExpr::Fn { body, .. } => {
            for statement in body {
                statement_variables(statement, names);
            }
        }
        TypedExpr::List { elements, tail, .. } => {
            for element in elements {
                expression_variables(element, names);
            }
            if let Some(tail) = tail {
                expression_variables(tail, names);
            }
        }
        TypedExpr::Call { fun, arguments, .. } => {
            expression_variables(fun, names);
            for argument in arguments {
                expression_variables(&argument.value, names);
            }
        }
        TypedExpr::BinOp { left, right, .. } => {
            expression_variables(left, names);
            expression_variables(right, names);
        }
        TypedExpr::Case {
            subjects, clauses, ..
        } => {
            for subject in subjects {
                expression_variables(subject, names);
            }
            for clause in clauses {
                expression_variables(&clause.then, names);
                if let Some(guard) = &clause.guard {
                    guard_variables(guard, names);
                }
            }
        }
        TypedExpr::RecordAccess { record, .. } => expression_variables(record, names),
        TypedExpr::PositionalAccess { record, .. } => expression_variables(record, names),
        TypedExpr::Tuple { elements, .. } => {
            for element in elements {
                expression_variables(element, names);
            }
        }
        TypedExpr::TupleIndex { tuple, .. } => expression_variables(tuple, names),
        TypedExpr::Todo { message, .. } | TypedExpr::Panic { message, .. } => {
            if let Some(message) = message {
                expression_variables(message, names);
            }
        }
        TypedExpr::Echo {
            expression,
            message,
            ..
        } => {
            if let Some(expression) = expression {
                expression_variables(expression, names);
            }
            if let Some(message) = message {
                expression_variables(message, names);
            }
        }
        TypedExpr::BitArray { .. } => {}
        TypedExpr::RecordUpdate {
            updated_record,
            constructor,
            arguments,
            ..
        } => {
            expression_variables(updated_record, names);
            expression_variables(constructor, names);
            for argument in arguments {
                expression_variables(&argument.value, names);
            }
        }
        TypedExpr::NegateBool { value, .. } | TypedExpr::NegateInt { value, .. } => {
            expression_variables(value, names);
        }
    }
}

fn guard_variables(guard: &TypedClauseGuard, names: &mut BTreeSet<EcoString>) {
    match guard {
        crate::ast::ClauseGuard::Var { name, .. } => {
            let _ = names.insert(name.clone());
        }
        crate::ast::ClauseGuard::Block { value, .. } => guard_variables(value, names),
        crate::ast::ClauseGuard::Not { expression, .. } => guard_variables(expression, names),
        crate::ast::ClauseGuard::BinaryOperator { left, right, .. } => {
            guard_variables(left, names);
            guard_variables(right, names);
        }
        crate::ast::ClauseGuard::TupleIndex { tuple, .. } => guard_variables(tuple, names),
        crate::ast::ClauseGuard::FieldAccess { container, .. } => {
            guard_variables(container, names)
        }
        crate::ast::ClauseGuard::ModuleSelect { .. }
        | crate::ast::ClauseGuard::Constant(_)
        | crate::ast::ClauseGuard::Invalid { .. } => {}
    }
}

fn function_arity(expression: &TypedExpr) -> usize {
    expression
        .type_()
        .fn_arity()
        .expect("zig codegen: function reference with non-function type")
}

/// True if `text` (a rendered statement) references `name` after its own
/// `const name = ...` binding line.
fn text_after_binding_uses(text: &str, name: &str) -> bool {
    match text.find(&format!("const {name} = ")) {
        Some(position) => {
            let after = &text[position + "const ".len() + name.len()..];
            after.contains(name)
        }
        None => text.contains(name),
    }
}

/// Quote an identifier with zig's raw identifier syntax. This side-steps
/// zig keyword collisions and allows `$` in generated names.
fn zig_identifier(name: &str) -> String {
    format!("@\"{name}\"")
}

/// Gleam string literal contents are close enough to zig's escape syntax to
/// pass through, except form feed which zig does not support.
fn zig_string_contents(value: &str) -> String {
    value.replace("\\f", "\\x0C")
}

/// Byte length of a Gleam string literal's decoded value, for string prefix
/// pattern slicing.
fn decoded_string_byte_length(value: &str) -> usize {
    let mut length = 0;
    let mut characters = value.chars().peekable();
    while let Some(character) = characters.next() {
        if character != '\\' {
            length += character.len_utf8();
            continue;
        }
        match characters.next() {
            Some('u') => {
                // \u{XXXX}
                let mut digits = String::new();
                if characters.peek() == Some(&'{') {
                    let _ = characters.next();
                    while let Some(&digit) = characters.peek() {
                        let _ = characters.next();
                        if digit == '}' {
                            break;
                        }
                        digits.push(digit);
                    }
                }
                let code_point = u32::from_str_radix(&digits, 16).unwrap_or(0);
                length += char::from_u32(code_point).map(char::len_utf8).unwrap_or(1);
            }
            Some(_) => length += 1,
            None => {}
        }
    }
    length
}
